version: '3.9'

services:
  database:
    image: postgres:15.6
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=notGonnaRevealThis2000
      - POSTGRES_USER=aizen
      - POSTGRES_DB=aizen_courses
