INSERT INTO author (author_id, author_last_name, author_name, author_bio, is_active) VALUES
  (1, 'Smith', 'John', 'John Smith is a bestselling author...', true),
  (2, 'Johnson', 'Emily', 'Emily Johnson is an award-winning writer...', true),
  (3, 'Brown', 'Michael', 'Michael Brown has published several novels...', true),
  (4, 'Davis', 'Jennifer', 'Jennifer Davis explores themes of love and loss...', true),
  (5, 'Anderson', 'David', 'David Anderson delves into the mysteries of the universe...', false),
  (6, 'Wilson', 'Sarah', 'Sarah Wilson is known for her gripping thrillers...', true),
  (7, 'Miller', 'Robert', 'Robert Miller stories transport readers to far-off lands...', false),
  (8, 'Harris', 'Jessica', 'Jessica Harris weaves tales of romance and adventure...', true),
  (9, 'Thompson', 'Andrew', 'Andrew Thompson works inspire readers to chase their dreams...', true),
  (10, 'Clark', 'Elizabeth', 'Elizabeth Clark novels touch the hearts of readers...', false),
  (11, 'Adams', 'Laura', 'Laura Adams writes captivating fantasy novels...', true),
  (12, 'Martin', 'Christopher', 'Christopher Martin explores the depths of human psychology...', true),
  (13, 'Wilson', 'Matthew', 'Matthew Wilson delves into the world of historical fiction...', true),
  (14, 'Robinson', 'Olivia', 'Olivia Robinson works inspire readers to embrace nature...', true),
  (15, 'Lewis', 'Benjamin', 'Benjamin Lewis crafts intricate mystery plots...', true),
  (16, 'Carter', 'Sophie', 'Sophie Carter stories transport readers to magical realms...', true),
  (17, 'Baker', 'Jonathan', 'Jonathan Baker pens heartwarming stories of friendship...', true),
  (18, 'Gray', 'Victoria', 'Victoria Gray explores the complexities of human relationships...', true),
  (19, 'Allen', 'Daniel', 'Daniel Allen novels are filled with suspense and twists...', true),
  (20, 'Parker', 'Emma', 'Emma Parker works shed light on important social issues...', true),
  (21, 'Brooks', 'Christopher', 'Christopher Brooks creates vivid worlds in his science fiction novels...', true),
  (22, 'Wood', 'Sophia', 'Sophia Wood stories captivate readers with their emotional depth...', true),
  (23, 'Barnes', 'Michael', 'Michael Barnes pens gripping crime thrillers...', true),
  (24, 'Clarkson', 'Emily', 'Emily Clarksons works transport readers to historical eras...', true),
  (25, 'Turner', 'Daniel', 'Daniel Turners novels are known for their poetic prose...', true),
  (26, 'Hill', 'Lucy', 'Lucy Hill delves into the realm of magical realism...', true),
  (27, 'Walker', 'Alexander', 'Alexander Walkers stories explore the human condition...', true),
  (28, 'Perez', 'Isabella', 'Isabella Perez writes heartwarming tales of family...', true),
  (29, 'Hughes', 'Sophie', 'Sophie Hughes crafts thought-provoking literary fiction...', true),
  (30, 'Scott', 'Jacob', 'Jacob Scott novels take readers on thrilling adventures...', true);