INSERT INTO category (category_id, category_name) VALUES
  (1, 'Front End Development'),
  (2, 'Personal Finances'),
  (3, 'Self Development'),
  (4, 'Microsoft Office'),
  (5, 'Machine Learning'),
  (6, 'Deep Learning'),
  (7, 'Graphic Design'),
  (8, 'Health and Wellness'),
  (9, 'Cooking and Recipes'),
  (10, 'Photography'),
  (11, 'Creative Writing'),
  (12, 'Entrepreneurship'),
  (13, 'Foreign Languages'),
  (14, 'Music Production'),
  (15, 'Fitness and Exercise'),
  (16, 'Travel and Adventure'),
  (17, 'Artificial Intelligence'),
  (18, 'Data Science'),
  (19, 'Cybersecurity'),
  (20, 'Social Media Marketing'),
  (21, 'Home Improvement'),
  (22, 'Parenting and Childcare'),
  (23, 'Fashion and Style'),
  (24, 'Environmental Conservation'),
  (25, 'Gardening'),
  (26, 'Mindfulness and Meditation'),
  (27, 'Film and Cinema'),
  (28, 'Sports and Recreation'),
  (29, 'Automotive Mechanics'),
  (30, 'Aerospace');